name: Daily (1 dag)

on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run daily
        run: |
          pip install requests
          python daily_run.py 1
